// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBrwahxy7nGZI6Z4ovx1qpGHL4YsziJYk',
    appId: '1:540736824551:web:01df71a0db6b943d3cee42',
    messagingSenderId: '540736824551',
    projectId: 'movies-8bae2',
    authDomain: 'movies-8bae2.firebaseapp.com',
    storageBucket: 'movies-8bae2.firebasestorage.app',
    measurementId: 'G-DNXSWK17QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLPhfIhq3vp1zIEb16dIXRJ2VUNwWXvx4',
    appId: '1:540736824551:android:4df60bf5a1062d213cee42',
    messagingSenderId: '540736824551',
    projectId: 'movies-8bae2',
    storageBucket: 'movies-8bae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbEuVY54cnDHbADwqJdGglGdT_SAZtgs',
    appId: '1:540736824551:ios:ec8418bf8a1d6afb3cee42',
    messagingSenderId: '540736824551',
    projectId: 'movies-8bae2',
    storageBucket: 'movies-8bae2.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbEuVY54cnDHbADwqJdGglGdT_SAZtgs',
    appId: '1:540736824551:ios:ec8418bf8a1d6afb3cee42',
    messagingSenderId: '540736824551',
    projectId: 'movies-8bae2',
    storageBucket: 'movies-8bae2.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBrwahxy7nGZI6Z4ovx1qpGHL4YsziJYk',
    appId: '1:540736824551:web:c4cd729bd5b278423cee42',
    messagingSenderId: '540736824551',
    projectId: 'movies-8bae2',
    authDomain: 'movies-8bae2.firebaseapp.com',
    storageBucket: 'movies-8bae2.firebasestorage.app',
    measurementId: 'G-YBYKW59S4G',
  );
}
